site_name: Artboch's Docs - Second semester
site_url: https://HARONavirus.github.io/ITMO_ICT_WebDevelopment_tools_2024-2025/
theme:
  name: material
nav:
  - Home: index.md
  - Lab 1:
    - Practice 1: practice-1/index.md
    - Practice 2: practice-2/index.md
    - Practice 3: practice-3/index.md
  - Lab 2:
    - Task 1: lab-2/task1.md
    - Task 2: lab-2/task2.md